### ISSUE TITLE
Canvas duplicates d3 chart and only uses the correct style once

### ISSUE THREAD

**Issue by jasonleehodges** [niklasvh/html2canvas#1261]
Please see this jsfiddle: http://jsfiddle.net/jasonleehodges/r37jadeh/29/

When I append the newly created canvas to the DOM my d3 chart has been duplicated on top of itself and the second one does not take the inline styles for the text object.

**Comment by felipemancini** [comment]
If you change the <svg> to a <span> for example it will work fine.
http://jsfiddle.net/r37jadeh/31/

**Comment by jasonleehodges** [comment]
That doesn't fix the style change on the text though.

**Comment by niklasvh** [comment]
Fixed in 1.0.0 http://jsfiddle.net/r37jadeh/32/

**Comment by tanlocnguyenbcm** [comment]
HI, i got FireFox 58.0 (64-Bit), and the Bug is still there.
http://jsfiddle.net/r37jadeh/32/

=( plz help
