### ISSUE TITLE
Abnormal letter spacing in Chrome / Chromium

### ISSUE THREAD

**Issue by christopherkade** [niklasvh/html2canvas#1272]
When calling:

```javascript
html2canvas(document.getElementsByClassName('console'), {
      onrendered: function(canvas) {
        var img = canvas.toDataURL()
        var iframe = '<iframe src="' + img + '" frameborder="0" style="border:0; top:0px; left:0px; bottom:0px; right:0px; width:100%; height:100%;" allowfullscreen></iframe>'
        var x = window.open();
        x.document.open();
        x.document.write(iframe);
        x.document.close();
      },
      letterRendering: true,
    });
```

Both with or without `letterRendering`, this is what Chrome outputs:

![html2canvasbug](https://user-images.githubusercontent.com/15229355/32991543-6ecd0bfe-cd35-11e7-97e4-8449d8808296.png)

When the output in Firefox is:

![screenshot-2017-11-19 http localhost](https://user-images.githubusercontent.com/15229355/32991555-89e65030-cd35-11e7-9597-a6c2e26cd6ae.png)

Any specific reason why it renders it like that?

**Comment by niklasvh** [comment]
The letter spacing (word spacing in this case) looks correct actually, what doesn't appear to be correct is the font family. Which version of html2canvas are you using? Can you replicate the issue on jsfiddle?

**Comment by christopherkade** [comment]
Thanks for your reply,

I'm using the version `0.5.0-beta4`.

What do you mean the work spacing looks correct? Are you referring to the first picture I have shared? Would the font create such spacing between words?

Note that I'm using `CodeMirror` for the text editor that is rendered, specifically an Angular wrapper: [ng2-codemirror](https://github.com/chymz/ng2-codemirror).

I tried reproducing the issue to no avail [here](https://jsfiddle.net/4L7fum1h/6/).

**Comment by LinkTree3** [comment]
I also found the same problem in firefox and chrome. If you have a letter-spacing css rule on the text it will render the text with large gaps between each word. This was not the case in version 0.4.1 it used to render text perfectly but it was missing pseudo elements(:before :after)

**Comment by christopherkade** [comment]
Once you remove the `letter-spacing` rule everything goes back to normal for you? I'm not using it, neither in my component's css nor in my custom `code-mirror`'s css file.

**Comment by LinkTree3** [comment]
Yes After removing the letter-spacing rule from the CSS the issue is gone. there are no large spaces between words. it's something in the rendering of the page at the part of the letter-spacing that is messing it up.

**Comment by LinkTree3** [comment]
Update! I just built the library from the latest sources on master and it works perfectly. everything looks really good so far. Previously I tried with the v0.5.0-beta4 release.

**Comment by christopherkade** [comment]
I don't use any `letter-spacing` property in my CSS and the issue is still present. I am using `v0.5.0-beta4` though.

**Comment by LinkTree3** [comment]
Try building from the latest master sources.

**Comment by christopherkade** [comment]
Done, and yet this does not solve the problem, the display remains the same.

**Comment by niklasvh** [comment]
Should be fixed with https://github.com/niklasvh/html2canvas/commit/77d258f1d8eeccf7e38235463a293b512c1ca3d0

**Comment by christopherkade** [comment]
Seems like the problem persists like such:

![screenshot_2017-12-18_09-56-43](https://user-images.githubusercontent.com/15229355/34100286-e5e578d8-e3d9-11e7-8536-e0b5480f126d.png)

Here's how I rendered the element:

```javascript
html2canvas(document.body).then(function(canvas) {      
      document.body.appendChild(canvas);
});    
```

I have downloaded the latest pre-release version as mentioned by you and replaced the old one.

**Comment by niklasvh** [comment]
@christopherkade does it fix it if you set the option `letterRendering: true`?

**Comment by christopherkade** [comment]
Sadly it does not, here's how I do it:

```typescript
let element = document.getElementById('console');
const options = {
  letterRendering: true
};

html2canvas(element, options).then(function(canvas) {      
  document.body.appendChild(canvas);
      
  var url = canvas.toDataURL();
  var img = '<img src="' + url + '" style="border:0;"></img>'
  var x = window.open();
  x.document.open();
  x.document.write(img);
  x.document.close();
});
```

Same result if I try the example given in the repository.

**Comment by christopherkade** [comment]
I have found a workaround for the matter (and it's not very clean):

```javascript
// Package used to detect the browser used by the user
const browser = detect();
const element = document.getElementById('console');

// Set up my options
let options = {};
// For some reason foreignObjectRendering solves the spacing issue on Chrome but gives an error on Firefox, so I detect the browser and apply the adequate options.
if (browser && browser.name === 'chrome') {      
  options = {
    useCORS: true,
    foreignObjectRendering: true
  };  
}

// Open the canvas in a new window
html2canvas(element, options).then(function(canvas) {
  const url = canvas.toDataURL();
  const img = '<img src="' + url + '" style="border:0;"></img>'
  const x = window.open();
  x.document.open();
  x.document.write(img);
  x.document.close();
});
```

Note that the error I get on Firefox when using the second option is as follows:

> Uncaught (in promise): [Exception... \"Method not implemented\"  ...

**Comment by ordas** [comment]
Same problem!!

**Comment by phillipegf** [comment]
Solved here by removing CSS attribute **font-variant-numeric: proportional-nums** from HTML body.

**Comment by mohafouad** [comment]
same problem with Arabic language any suggestion please ?

**Comment by 2xSamurai** [comment]
@mohafouad  +1

**Comment by mohafouad** [comment]
@2xSamurai no :(

**Comment by maaoui** [comment]
I have fixed this also by going to the div I want to screenshot and then I set the " font-variant: normal; " this has worked for me hope it helps .

**Comment by Malarkey-Jhu** [comment]
fixed if I add `font-variant: normal !important`  to outer div of whole content (in antd project)

**Comment by zxr3680166** [comment]
same problem, drived me crazy
![image](https://user-images.githubusercontent.com/4338858/60407454-77255300-9bed-11e9-92a5-cb45a88255b7.png)

font-variant: normal !important  not working

**Comment by nora-white** [comment]
@Malarkey-Jhu's answer solved my problem. 

The problem I had: Font family wasn't working and spacing was very wonky. Sometimes I would have overlapping letters.

What I do: During export I call element.style.setProperty('font-variant', 'normal') on the element with the text, and this allows the font-family to show properly, and the spacing to not be all wonky. Then I remove that property after I've finished exporting.

**Comment by spideeee** [comment]
Based on the above solutions, this issue is fixed for me by changing `-webkit-font-variant-ligatures` and `font-variant-ligatures` to `normal` in codemirror css file. I am using CodeMirror version `5.42.2`.

**Comment by chriszrc** [comment]
For me, this problem was caused by trying to take screenshots of text that was using a custom font (even if the fonts were loaded from the same domain). I had to change the font back to something built-in in the interim clone h2c creates, then everything worked perfectly (minus the custom fonts...):

```
html2canvas(element, {
      // removeContainer: false, //useful for testing changes to the interim iframe copy
      onclone: (document: Document) => {
        Array.from(
          document
            .querySelector(".analysis-container .ng-star-inserted")
            .children[0].querySelectorAll("*"),
        ).forEach((e) => {
          let existingStyle = e.getAttribute("style") || "";
          e.setAttribute("style", existingStyle + "; font-family: Helvetica, sans-serif !important");
        });
      },
    }).then(function (canvas) { //...etc
```
