### ISSUE TITLE
html2canvas  not  work  when the html contains a canvas element

### ISSUE THREAD

**Issue by mengwuhen** [niklasvh/html2canvas#1311]
### Bug reports:
I am using html2canvas in a react Project. I found that html2canvas  not  work  when the html contains a canvas element. The canvas area will show empty.

### Specifications:
**this is the html picture**
![image](https://user-images.githubusercontent.com/22239802/33930049-947eb254-e026-11e7-9db6-0f554826e1ba.png)

**this is the convert to canvas picture** 

![image](https://user-images.githubusercontent.com/22239802/33930114-d28ad58c-e026-11e7-9a25-d5d85f293d3d.png)

in the canvas area , I use  'echarts-for-react'  to draw a Radar map。But when I clcik  Generate pictures  Button ， the dowload picture is not complete

 * html2canvas version tested with: 1.0.0-alpha.4
 * Browser & version: Chrome   60.0.3112.7
 * Operating system: windows

**Comment by bigfacewo** [comment]
I have the same problem.

**Comment by niklasvh** [comment]
Could you share an example on jsfiddle?

**Comment by outerbound** [comment]
same problem. i have chartjs graphs on page, they are no longer rendering. used to render in previous version

**Comment by outerbound** [comment]
I have created a fiddle to show the problem
https://jsfiddle.net/outerbound/v7p71wzr/

**Comment by ZeroGravity100500** [comment]
problem is in removing container form DOM before rendering

**Comment by JasonDung** [comment]
I have the same problem. marker...

**Comment by bigfacewo** [comment]
Maybe html2canvas can not work with [gridstack.js](https://github.com/gridstack/gridstack.js)

**Comment by enanchen** [comment]
Had the same problem with using chart.js with vue(vue-chart.js) and it only happens in Chrome

**Comment by Nemo0915** [comment]
I have the same problem, html2canvas can not work with gridstack.js, when i use html2canvans with gridstack, all elements get stacked at the top.
![image](https://user-images.githubusercontent.com/12935964/34144145-3d9162da-e4cb-11e7-84bd-7146e5be7246.png)

**Comment by bigfacewo** [comment]
@Nemo0915 I build a [jsfiddle](http://jsfiddle.net/bigfacewo/t8Lu82te/2/?utm_source=website&utm_medium=embed&utm_campaign=t8Lu82te#&togetherjs=aNUKoO5PvO) with gridstack.js, but it's work fine.

**Comment by otherlite** [comment]
+1

**Comment by ArrayZheng** [comment]
same problem,Firefox is ok but Chorme can not work

**Comment by Nemo0915** [comment]
@bigfacewo thanks for your reply,it's the screenshot of your jsfiddle, the button has been stacked to the top too,  and the result is same whether in FF or Chrome.
![image](https://user-images.githubusercontent.com/12935964/34194648-ade84c00-e594-11e7-8288-86577a934a69.png)

**Comment by bigfacewo** [comment]
@Nemo0915 I found the 0.5 version work normal,[jsfiddle](http://jsfiddle.net/bigfacewo/t8Lu82te/6/). the screenshot is:
![qq 20171220150328](https://user-images.githubusercontent.com/31603897/34195122-f344056c-e596-11e7-8c53-c97e7e8cd578.png)
The 1.0.0-alpha4 version,[jsfiddle](http://jsfiddle.net/bigfacewo/t8Lu82te/8/),it's can not work on chrome, But i didn't find the problem that the elements were stacked on the top. this is the screenshot on Firefox:
![qq 20171220150946](https://user-images.githubusercontent.com/31603897/34195321-dd50b8e4-e597-11e7-8ac0-f3f75e30c9ab.png)

**Comment by IxAres** [comment]
you can add option: removeContainer: false to fixed this problem temporarily....

**Comment by enanchen** [comment]
Thanks @IxAres, it solves my problem.

**Comment by niklasvh** [comment]
Fixed in https://github.com/niklasvh/html2canvas/commit/38749bc4b6a861f778a915491fc7d84fea6e1a2f

**Comment by omeriko** [comment]
i've tried adding removeContainer: false, but the problem still exists on mobile Chrome

**Comment by nehachaudhary** [comment]
@niklasvh it doesn't work at all. I am using version 1.0.0-rc.5 of this application. 
<img width="368" alt="Screenshot 2020-02-17 at 10 54 42 AM" src="https://user-images.githubusercontent.com/2748623/74625900-e8f9df00-5173-11ea-8919-54e75b9eb810.png">

**Comment by steele-cjf** [comment]
hey,what solution?

**Comment by MrG2333** [comment]
2020 the problem is still here.

**Comment by nwoodhouse** [comment]
+1 I'm also seeing this behaviour.

**Comment by IAmRC1** [comment]
Problem still exists

**Comment by g0d0** [comment]
Problem still exists with Chart.js.

**Comment by Rajeshgtstpl** [comment]
Hey there I am getting the same issue with Mapbox inside and element can you please help here.
I have also tried removeContainer: false but it didn't work for me.

**Comment by AchoArnold** [comment]
@Rajeshgtstpl I had a similar issue  with mapbox. I solved it by setting `preserveDrawingBuffer: true` in the mapbox options.

**Comment by andreassoegaard** [comment]
I solved this issue by putting image.crossOrigin = 'anonymous' on the image element before passing it to drawImage, like this:

`const x = this.$refs['vignet-' + this.data.index]
      const ctx = x.getContext('2d')
      const image = new Image()
      image.crossOrigin = 'anonymous'
      image.onload = () => {
        ctx.canvas.width = image.naturalWidth
        ctx.canvas.height = image.naturalHeight
        ctx.fillStyle = this.data.fontColor
        ctx.fillRect(0, 0, image.naturalWidth, image.naturalHeight)
        // set composite mode
        ctx.globalCompositeOperation = 'destination-in'
        ctx.drawImage(image, 0, 0)
        this.loaded = true
      }
      image.src = this.vignetUrl`

Hope it can help someone :)

**Comment by tejasdotchavan** [comment]
Hi guys, I am having similar canvas export issue but with a threejs scene

**Comment by jimmyangel** [comment]
@AchoArnold ```preserveDrawingBuffer: true``` worked for me for Mapbox, thanks.

Question: have you noticed a performance impact?

**Comment by Nurbek0525** [comment]
> I'm not using Chart.js, but had the same problem with canvases where i used drawImage. Solved the issue by putting image.crossOrigin = 'anonymous' on the image element before passing it to drawImage, like this:
> 
> `image.crossOrigin = 'anonymous'`
> 
> Hope it can help someone :)

it saved my life thanks

**Comment by SalahAdDin** [comment]
> > I'm not using Chart.js, but had the same problem with canvases where i used drawImage. Solved the issue by putting image.crossOrigin = 'anonymous' on the image element before passing it to drawImage, like this:
> > `image.crossOrigin = 'anonymous'`
> > Hope it can help someone :)
> 
> it saved my life thanks

It does not work.

**Comment by sachin-sprinkle** [comment]
Is there any fix for this?? Still facing this issue.

**Comment by SalahAdDin** [comment]
> Is there any fix for this?? Still facing this issue.

We had to use a proxy server to avoid this problem.

**Comment by rishhavv** [comment]
Found any fix?

**Comment by arvind-kumar-esri** [comment]
> preserveDrawingBuffer: true

Where we add this into code

**Comment by linilini** [comment]
> [于38749bc](https://github.com/niklasvh/html2canvas/commit/38749bc4b6a861f778a915491fc7d84fea6e1a2f)修复[](https://github.com/niklasvh/html2canvas/commit/38749bc4b6a861f778a915491fc7d84fea6e1a2f)

The statistical chart is good in Chrome, but there is a problem with Safari and the statistical chart is not available.
