### ISSUE TITLE
IE 11 issue, Error: Uncaught (in promise): Error: Member not found.

### ISSUE THREAD

**Issue by Prabhat2404** [niklasvh/html2canvas#1374]
Got error : "html2canvas $npm_package_version. Error: Uncaught (in promise): Error: Member not found." 
When i try to get canvas.

Code:
 html2canvas(document.querySelector("#capture")).then(function (canvas) {
            console.log(canvas);
            document.getElementById('here-appear-theimages').appendChild(canvas);
        });
Using:
Angular version : 4.0.1
OS: Window 10
Also added refrence of: https://cdn.jsdelivr.net/npm/es6-promise/dist/es6-promise.auto.js
Attached error screenshot.

![error_ie_11](https://user-images.githubusercontent.com/16957593/34688771-3fd75ba8-f4d9-11e7-91ae-669fcb875197.png)

**Comment by jelkins8** [comment]
I added a link to the following promise library and it seemed to fix IE 11 for us.
https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.3.4/bluebird.min.js

**Comment by niklasvh** [comment]
Without code to reproduce the error I can't really help.

**Comment by Prabhat2404** [comment]
This is demo sample i have hosted on GitHub you can see - [GitHub Html2Canvas Demo](https://prabhat2404.github.io/#/pages/dashboard)

Full code is also uploaded on github, if you want to see: [Code package](https://github.com/Prabhat2404/prabhat2404.github.io/blob/master/ng2-admin-with-html2canvas.tgz)

How to run project:
1) Unzip package
2) Run command: "npm install" from directory to install dependency 
3) To run project command: "npm start"

**Comment by Prabhat2404** [comment]
Hi @jelkins8,

I have tried this solution but its not working for me.
This is demo sample i have hosted on GitHub you can see - [GitHub Html2Canvas Demo](https://prabhat2404.github.io/#/pages/dashboard)

Thanks

**Comment by simonpinn** [comment]
Hi @niklasvh , 
I too have tried with es6-promise and bluebird without success in IE11, can confirm that [GitHub Html2Canvas Demo](https://prabhat2404.github.io/#/pages/dashboard) also fails in IE for me.
I receive ```html2canvas: Error: Member not found.``` followed by ```Possible Unhandled Promise Rejection: Error: Member not found.```
thanks!

**Comment by GPranali** [comment]
I am facing the same issue for html2canvas: member not found for IE.
For chrome it is working perfectly fine.
Please update if any solution. Thanks

**Comment by simonpinn** [comment]
I've reproduced the issue and located the cause, it happens in the ```createElementClone``` function when it attempts to access the ```cssText``` property, for some reason when using font-awesome, an element with ```fa-spin``` throws this error in IE when accessing the property.

As follows works:

```
if (node instanceof HTMLStyleElement && node.sheet && node.sheet.cssRules) {
              var style = node.cloneNode(false);
                  var css = [].slice.call(node.sheet.cssRules, 0).reduce(function (css, rule) {
                    try {
                      if (rule && rule.cssText) {
                        return css + rule.cssText;
                      }
                      return css;
                    } catch (err) {
                      _this3.logger.log('Unable to access cssText property', rule.name);
                    }
                  }, '');
                  style.textContent = css;

                return style;
            }
```
Note the try...catch.

I'll raise a PR.

**Comment by simonpinn** [comment]
Appears to cause a regression in ```Firefox 58.0.0 (Linux 0.0.0) /tests/reftests/background/radial-gradient2.html Should render untainted canvas FAILED``` @niklasvh any chance you could take a look?

thanks

**Comment by Prabhat2404** [comment]
Hi @niklasvh,
Have you got any solution for this, is any one looking on this issue ?

Thanks

**Comment by simonpinn** [comment]
Hi @Prabhat2404, the fix I've proposed in https://github.com/niklasvh/html2canvas/pull/1415 works great for me, however it does fail one of the radial gradient tests, which I've asked @niklasvh to have a look at. The issue occurs for me when using font-awesome icons, in particular fa-spin.

**Comment by stephanepericat** [comment]
same problem here

**Comment by oleksandrstarov** [comment]
The issue is still exists for IE in case we try to print html code.
Is there any workaround to not modify library source code and solve the issue?

**Comment by evgenyjam** [comment]
+1

**Comment by BrunoMarc** [comment]
+1

**Comment by mr0n3** [comment]
+1

**Comment by evgenyjam** [comment]
[It](https://github.com/niklasvh/html2canvas/pull/1415/commits/b280cdd27000ef1896e15b8645dc3fcacdcf0d6a) helps for me!

**Comment by cyouden** [comment]
@evgenyjam That solution still has a bug, you need to add an empty string as the initial value for reduce.

I mentioned that on the PR, but the author hasn't updated it yet. But with that change it works for me.

**Comment by cyouden** [comment]
@BrunoMarc No, it's the last argument for reduce, so:
.reduce((css, rule) => { /* code */ }, "")

(E.g. see the code the change is proposed to replace in that diff, it correctly uses the initial value for reduce.)

**Comment by BrunoMarc** [comment]
@cyouden Thanks for the response! I have inserted this code in html2canvas.js but the Member not found still persist, any ideas?
`  if (node instanceof HTMLStyleElement && node.sheet && node.sheet.cssRules) {
                const css = [].slice
                    .call(node.sheet.cssRules, 0)
                    .reduce((css, rule) => {
                                            try {
                                                if (rule && rule.cssText) {
                                                  return css + rule.cssText;
                                                }
                                                return css;
                                              } catch (err) {
                                                this.logger.log('Unable to access cssText property', rule.name);
                                                return css;
                                              }
                                        }, '');
                const style = node.cloneNode(false);
                style.textContent = css;
                return style;
               }`

**Comment by cyouden** [comment]
@BrunoMarc No idea, that change was enough to get it working for me.

**Comment by simonpinn** [comment]
Hey - sorry to be late to the party, I've just committed a change with the default empty string for the reduce, as suggested, hope that helps!
cheers

**Comment by simonpinn** [comment]
@niklasvh @BrunoMarc @cyouden good news the build is passing for the PR
Sorry I didn't update earlier, I'd actually moved on from moving the library, I'd come across the bug while using it in a spike. Hope it helps!

**Comment by bandacs** [comment]
@simonpinn I am trying to use html2canvas-1.0.0-alpha.10 version for my angular 4 code. I am getting following error in all browsers. And only part of html is getting printed.



34487ms html2canvas: html2canvas $npm_package_version
core.js:1427 ERROR Error: Uncaught (in promise): undefined
    at resolvePromise (zone.js:824)
    at resolvePromise (zone.js:795)
    at eval (zone.js:873)
    at ZoneDelegate.invokeTask (zone.js:425)
    at Object.onInvokeTask (core.js:4747)
    at ZoneDelegate.invokeTask (zone.js:424)
    at Zone.runTask (zone.js:192)
    at drainMicroTaskQueue (zone.js:602)
    at ZoneTask.invokeTask [as invoke] (zone.js:503)
    at invokeTask (zone.js:1540)
defaultErrorLogger @ core.js:1427
ErrorHandler.handleError @ core.js:1488
next @ core.js:5503
schedulerFn @ core.js:4342
SafeSubscriber.__tryOrUnsub @ Subscriber.js:239
SafeSubscriber.next @ Subscriber.js:186
Subscriber._next @ Subscriber.js:127
Subscriber.next @ Subscriber.js:91
Subject.next @ Subject.js:56
EventEmitter.emit @ core.js:4322
(anonymous) @ core.js:4778
ZoneDelegate.invoke @ zone.js:392
Zone.run @ zone.js:142
NgZone.runOutsideAngular @ core.js:4704
onHandleError @ core.js:4778
ZoneDelegate.handleError @ zone.js:396
Zone.runGuarded @ zone.js:158
_loop_1 @ zone.js:702
api.microtaskDrainDone @ zone.js:711
drainMicroTaskQueue @ zone.js:610
ZoneTask.invokeTask @ zone.js:503
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1566
Logger.js:36 53695ms html2canvas: Document cloned, using computed rendering
Logger.js:36 80495ms html2canvas: Starting node parsing
2Length.js:32 Invalid value given for Length: "auto"
Length @ Length.js:32
(anonymous) @ margin.js:18
parseMargin @ margin.js:17
NodeContainer @ NodeContainer.js:104
parseNodeTree @ NodeParser.js:63
NodeParser @ NodeParser.js:38
(anonymous) @ Window.js:86
ZoneDelegate.invoke @ zone.js:392
onInvoke @ core.js:4756
ZoneDelegate.invoke @ zone.js:391
Zone.run @ zone.js:142
(anonymous) @ zone.js:873
ZoneDelegate.invokeTask @ zone.js:425
onInvokeTask @ core.js:4747
ZoneDelegate.invokeTask @ zone.js:424
Zone.runTask @ zone.js:192
drainMicroTaskQueue @ zone.js:602
ZoneTask.invokeTask @ zone.js:503
ZoneTask.invoke @ zone.js:488
timer @ zone.js:2040
setInterval (async)
scheduleTask @ zone.js:2056
ZoneDelegate.scheduleTask @ zone.js:411
onScheduleTask @ zone.js:301
ZoneDelegate.scheduleTask @ zone.js:405
Zone.scheduleTask @ zone.js:236
Zone.scheduleMacroTask @ zone.js:259
(anonymous) @ zone.js:2072
proto.(anonymous function) @ zone.js:1366
cloneWindow.onload.cloneIframeContainer.onload.documentClone.onreadystatechange @ Clone.js:496
wrapFn @ zone.js:1166
ZoneDelegate.invokeTask @ zone.js:425
onInvokeTask @ core.js:4747
ZoneDelegate.invokeTask @ zone.js:424
Zone.runTask @ zone.js:192
ZoneTask.invokeTask @ zone.js:499
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1566
Logger.js:36 83270ms html2canvas: Finished parsing node tree

**Comment by bandacs** [comment]
@simonpinn I am using the way as follows. Is there any issue with latest version 1.0.0-alpha.10 in tyscript (angular 4) code? Can you please help me with solution. I am very much in need.

savePDFSample() {
    let element = document.getElementById('webcastCalendarId');
    let hgt = this.events.length*100;
    html2canvas(element).then(function(canvas){
      var img = canvas.toDataURL("image/png");
      var hratio = 0.80;
      var pdf = hgt >= 700 ? new jsPDF('l','pt',[hgt, 1000]) : new jsPDF('l','pt',[700, 1000]);
      var width = pdf.internal.pageSize.width;    
      var height = hgt >= 700 ? pdf.internal.pageSize.height * hratio : hgt * hratio; 
      pdf.addImage(img,'jpeg',40, height*0.1, width*0.92, height);
      pdf.save('webcastCalendar.pdf');
  });
  }

**Comment by simonpinn** [comment]
@bandacs this issue is for solving an IE 11 error for uncaught promises, please raise an issue against the alpha.10 build, if you are having a problem.

thanks

**Comment by bandacs** [comment]
@simonpinn @cyouden 
Following up the above defect. I found the other library (dom-to-image) for Chrome and and Firefox browsers. But the issue still continues in IE. When I go through the above conversation, I got to know that empty string workaround fixes the defect. Is that work around working? Also may I know when that change will be included in library?

**Comment by niklasvh** [comment]
Fix merged in v1.0.0-alpha.11

**Comment by tkantharia** [comment]
I have reactjs project and i did npm install for updates. but in IE 11 browser its still showing me Member not found error. Please help

**Comment by sarahbenjamin** [comment]
I am using the  v1.0.0-alpha.11 and it works great in Chrome but getting an error on IE 11 on the same lines
 html2canvas(panel).then(canvas => {      
            var img = canvas.toDataURL("image/png");    
        });

**Comment by ulrichmueller** [comment]
Hello. Same error for me. Our customer uses IE11 as default ...

**Comment by fasidOnGit** [comment]
Fixed it!!
Open `node_modules/html2canvas/dist/html2canvas.js`
Search for `if (rule && rule.cssText)`
and Change it to `if (rule && **typeof rule.cssText === 'string'**)`

**Comment by niklasvh** [comment]
fixed with https://github.com/niklasvh/html2canvas/commit/bc270bb2116480a8ae08d3d9601f2b6118b44da3

**Comment by seshadriallimani** [comment]
Hi All,
I am also having the below issue which fixed:
Open node_modules/html2canvas/dist/html2canvas.js
Search for if (rule && rule.cssText)
and Change it to if (rule && typeof rule.cssText === 'string')
This fixed the problem for me in IE11 :)

How can i get a new published version of it to use in my project? currently i tested by editing in node-modules in my local environment. to push it production need a new published version of 'html2canvas' version? can you please help me to get it?

**Comment by seshadriallimani** [comment]
Currently i am using the "html2canvas": "^1.0.0-rc.1", which doesn't have the fix.

**Comment by seshadriallimani** [comment]
Hi @niklasvh, can you tell me when new version will be release with the fix for issue #1374 . Eagerly waiting to see fix in the version.
