### ISSUE TITLE
Text overlaps when it naturally wraps to the next line

### ISSUE THREAD

**Issue by mdbollman** [niklasvh/html2canvas#2213]
When text automatically line breaks and the next line starts with some specific characters like one of `/ [ ] -`, subsequent text will overlap. 

I realize there are other similar open issues but either fixes suggested don't solve the problem (eg. css from #1755), or are not quite the same thing. Definitely related to others though. 

Pen:
https://codepen.io/mdbollman/pen/YzyNqzz

### Specifications:

 * html2canvas version tested with: 1.0.0-rc.5
 * Browser & version: Mac Safari, iOS Safari, Mac Chrome, Mac Firefox, Mac Edge, Windows Chrome, Windows Old Edge
 * Operating system: Mac, iOS, Windows

**Comment by wufeng87** [comment]
Any good news here? I got the same problem: https://github.com/niklasvh/html2canvas/issues/2231

**Comment by christophestahl** [comment]
Hi folks. Any update on this? We keep on coming across issues on our website because of this. 
Thanks!

**Comment by mdbollman** [comment]
Unfortunately this issue still exists. We haven't had enough time to look into fixing it ourselves either.

**Comment by itsanmax** [comment]
Hello everyone! Is there any update on this issue? Thanks!

**Comment by bb-mt** [comment]
Discovered the exact same problem.  Still no help?

**Comment by JD2k** [comment]
Same problem here. A fix would be very much appreciated.

**Comment by niklasvh** [comment]
This should be fixed

**Comment by flwzz** [comment]
the problem still exists in the latest version , so any resolution for this?

**Comment by fimars** [comment]
the problem still exists, and ios13 appears more frequently.

**Comment by chea1tei** [comment]
Any update on this yet? The text are not wrapping correctly even on the latest version. This is happening only on safari
