### ISSUE TITLE
background-clip: text (-webkit-background-clip) not working

### ISSUE THREAD

**Issue by NurulAlomAdor** [niklasvh/html2canvas#2366]
background-clip: text is not working which is needed for create gradien text. Please tell me anyone if there is any sollution for it. 
Here is some screenshot.

In browser:
![image](https://user-images.githubusercontent.com/66767267/94339689-92178a80-001d-11eb-825c-dd3d3238a55b.png)

On created image of html2canvas:
![image](https://user-images.githubusercontent.com/66767267/94339706-b3787680-001d-11eb-824c-775092f2fdc2.png)

**Comment by dikshantrajput** [comment]
Just add one more property i.e
-webkit-text-fill-color : transparent;

**Comment by NurulAlomAdor** [comment]
> Just add one more property i.e
> -webkit-text-fill-color : transparent;

```-webkit-text-fill-color : transparent;``` is already added.

**Comment by dikshantrajput** [comment]
can you show the full code in which this part is covered

**Comment by NurulAlomAdor** [comment]
> can you show the full code in which this part is covered

It's not css/html code related problem. For fixing it, it's needed to add custom code in html2canvas.js file. Like https://github.com/canoncarlson fix the ```object-fit: cover``` issue on https://github.com/niklasvh/html2canvas/issues/1064 by adding custom code in html2canvas.js file. 
But I am not so export in javascript to add custom code in html2canvas.js file and fix it. I need some one's help who is export in Javascript like https://github.com/canoncarlson

**Comment by NurulAlomAdor** [comment]
Finaly after work of 6 days, i fixed the problem by writing custom code inside HTML2CANVAS.js. Here is demo: 
![image](https://user-images.githubusercontent.com/66767267/94945676-d82c8c80-04fc-11eb-83a8-afe720539745.png)

JSFiddle link - https://jsfiddle.net/9vhy58jp/

**Comment by Muneem** [comment]
What is the solution for it? I am also facing this issue

**Comment by suman-majhi** [comment]
@NurulAlomAdor its still not working in the library,
are the changes merged with the main branch?

**Comment by Amy0714Angela** [comment]
> @NurulAlomAdor its still not working in the library, are the changes merged with the main branch?

I am facing the same issue,how do you fix it?

**Comment by Amy0714Angela** [comment]
> Finaly after work of 6 days, i fixed the problem by writing custom code inside HTML2CANVAS.js. Here is demo: ![image](https://user-images.githubusercontent.com/66767267/94945676-d82c8c80-04fc-11eb-83a8-afe720539745.png)
> 
> JSFiddle link - https://jsfiddle.net/9vhy58jp/

I'm trying to use this code,but the final pic is overall to the right
![image](https://user-images.githubusercontent.com/27943611/153160405-545b4076-64ed-4e1a-a183-d4e0708e69c9.png)

**Comment by czepesch** [comment]
> What is the solution for it? I am also facing this issue

I'm using Tailwind and Rails, but maybe it will be helpful for someone.
Tailwind have CSS class **bg-clip-text**, but it is not working without explicitly adding in my CSS file:

```
.bg-clip-text {
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
}
```

**Comment by kooriookami** [comment]
@nurulalamador Could you make a PR for the current version?

**Comment by kooriookami** [comment]
> > Finaly after work of 6 days, i fixed the problem by writing custom code inside HTML2CANVAS.js. Here is demo: ![image](https://user-images.githubusercontent.com/66767267/94945676-d82c8c80-04fc-11eb-83a8-afe720539745.png)
> > JSFiddle link - https://jsfiddle.net/9vhy58jp/
> 
> I'm trying to use this code,but the final pic is overall to the right ![image](https://user-images.githubusercontent.com/27943611/153160405-545b4076-64ed-4e1a-a183-d4e0708e69c9.png)

I found a code that solves the problem perfectly. https://www.cnblogs.com/loveamyforever/p/15878690.html
@Amy0714Angela  Are you the author of it?

**Comment by tanatuosi** [comment]
> > > Finaly after work of 6 days, i fixed the problem by writing custom code inside HTML2CANVAS.js. Here is demo: ![image](https://user-images.githubusercontent.com/66767267/94945676-d82c8c80-04fc-11eb-83a8-afe720539745.png)
> > > JSFiddle link - https://jsfiddle.net/9vhy58jp/
> > 
> > 
> > I'm trying to use this code,but the final pic is overall to the right ![image](https://user-images.githubusercontent.com/27943611/153160405-545b4076-64ed-4e1a-a183-d4e0708e69c9.png)
> 
> I found a code that solves the problem perfectly. https://www.cnblogs.com/loveamyforever/p/15878690.html @Amy0714Angela Are you the author of it?

I'm trying to use the code from https://www.cnblogs.com/loveamyforever/p/15878690.html, but I'm encountering some problems when there's some text in front of the gradient text

**Comment by chnkarl** [comment]
> Finaly after work of 6 days, i fixed the problem by writing custom code inside HTML2CANVAS.js. Here is demo: ![image](https://user-images.githubusercontent.com/66767267/94945676-d82c8c80-04fc-11eb-83a8-afe720539745.png)
> 
> JSFiddle link - https://jsfiddle.net/9vhy58jp/

It works for me, u are aswsome cool

**Comment by lixingjuan** [comment]
I solved it by svg, also can custom font-size, font-weight ..., etc.
 
```svg   
 <svg width={"0.64rem"} height="0.45rem" xmlns="http://www.w3.org/2000/svg">
      <defs>
        <linearGradient id="grad" x1="0%" y1="0%" x2="100%" y2="0%">
          <stop
            offset="5%"
            style={{
              stopColor: "#ffa200",
            }}
          />
          <stop
            offset="100%"
            style={{
              stopColor: "#fc5a00",
            }}
          />
        </linearGradient>
      </defs>
      <text
        x="50%"
        y="50%"
        fill="url(#grad)"
        text-anchor="middle"
        font-size="0.32rem"
        font-family="Arial"
        font-weight="600"
        line-height="45"
        dy=".38em"
      >
        复盘
      </text>
    </svg>

```
