### ISSUE TITLE
CanvasRenderingContext2D.createPattern: Passed-in canvas has width 0

### ISSUE THREAD

**Issue by abdurrahmanyildirim** [niklasvh/html2canvas#2697]
### Bug reports:

I had this error when i try to take screenshot at firefox. "DOMException: CanvasRenderingContext2D.createPattern: Passed-in canvas has width 0"

### Specifications:

 * html2canvas version tested with: v1.3.2
 * Browser & version: Firefox & 91.0.2
 * Operating system: Windows

### Solution

add this code to line 7235
``` 
 width = isNaN(width) || width === 0 ? 1 : width;
 height = isNaN(height) || height === 0 ? 1 : height;
```

**Comment by immissile** [comment]
> ### Bug reports:
> I had this error when i try to take screenshot at firefox. "DOMException: CanvasRenderingContext2D.createPattern: Passed-in canvas has width 0"
> 
> ### Specifications:
> * html2canvas version tested with: v1.3.2
> * Browser & version: Firefox & 91.0.2
> * Operating system: Windows
> 
> ### Solution
> add this code to line 7235
> 
> ```
>  width = isNaN(width) || width === 0 ? 1 : width;
>  height = isNaN(height) || height === 0 ? 1 : height;
> ```

Could you please show the code snippet(context)?  thx.

**Comment by Elanchezhiyan-AIT** [comment]
@immissile & @abdurrahmanyildirim 

Is this issue fixed in JS file also? Because still I'm able to reproduce this issue with the latest html2canvas js file.

![image](https://user-images.githubusercontent.com/83453631/204540963-66f49de0-bda2-4c69-b4cc-5a235da75bce.png)

**Comment by magiclen** [comment]
html2canvas still has this bug on Firefox.

**Comment by Elanchezhiyan-AIT** [comment]
Hi @magiclen ,

Can you please check this out?

[html2canvas.min.zip](https://github.com/niklasvh/html2canvas/files/10857593/html2canvas.min.zip)


Thanks,
Elanchezhiyan P

**Comment by magiclen** [comment]
@Elanchezhiyan-AIT 

Thank you. But it's still not working...

**Comment by magiclen** [comment]
Hi, @Elanchezhiyan-AIT 

I made a simple case to reproduce this bug.

```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>html2canvas</title>
    <script src="./html2canvas.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>
<body>
    <div class="container py-5">
        <input type="text" class="form-control" value="Hello" />
        <div class="form-check">
          <input type="checkbox" class="form-check-input" value="">
          <label class="form-check-label" for="flexCheckDefault">World</label>
        </div>
    </div>
    
    
    <script>
        setInterval(() => {
            for (e of document.getElementsByTagName("canvas")) {
                e.remove();
            }
            html2canvas(document.body).then((result) => {
                document.body.appendChild(result);
            });
        }, 1000);
    </script>
</body>
</html>
```

When the bootstrap CSS is imported and the element which we want to shot contains an checkbox input and the checkbox is checked, `Uncaught (in promise) DOMException: CanvasRenderingContext2D.createPattern: Passed-in canvas has width 0` occurs.

**Comment by Elanchezhiyan-AIT** [comment]
Hi @magiclen ,

Please Checkout the JSFiddle Link below.

Link: https://jsfiddle.net/ElanchezhiyanP/j70wnz5L/

Thanks,
Elanchezhiyan P

**Comment by magiclen** [comment]
@Elanchezhiyan-AIT 

Thanks for helping creating this page.

Did you successfully reproduce the bug that I found?

I tried Firefox, Chrome, Opera. Only Firefox has this trouble.

**Comment by Elanchezhiyan-AIT** [comment]
Hi @magiclen ,

I was able to reproduce it only in Firefox browser. Let me check it and get back to you with some sort of solution buddy!

Thanks,
Elanchezhiyan P

**Comment by Elanchezhiyan-AIT** [comment]
Hi @magiclen ,

Please take a look at the below JSFiddle and now it works fine in all the browsers. Let me know if there is any other issues

Link: https://jsfiddle.net/h025ck4L/

Thanks,
Elanchezhiyan P

**Comment by magiclen** [comment]
@Elanchezhiyan-AIT 

Hi, thanks for the help. But on my computer and smart phone, it still doesn't work.

Here is my screen record:
https://youtu.be/CXCnUJS5SPY

**Comment by Elanchezhiyan-AIT** [comment]
@magiclen ,

I need to check with your system only buddy!. If possible, please let me know.

Thanks,
Elanchezhiyan P

**Comment by magiclen** [comment]
Hi @Elanchezhiyan-AIT ,

I tried

* Linux Mint 21.1 + Firefox 111.0
* Windows 7 64bit + Firefox 102.8.0esr
* Windows XP 32bit + Firefox 52.9.0
* Android 13 + Firefox 111.0.1

They all have the same behavior.

**Comment by Elanchezhiyan-AIT** [comment]
Hi @magiclen ,

Please check with the attached zip file.

[html2canvas.min.zip](https://github.com/niklasvh/html2canvas/files/10860779/html2canvas.min.zip)

Thanks,
Elanchezhiyan P

**Comment by magiclen** [comment]
@Elanchezhiyan-AIT

It works! But how?

**Comment by Elanchezhiyan-AIT** [comment]
@magiclen ,

I'm also little bit confused with this scenario. However, the given solution works fine. Please host the application with the given min file so that the error might be rectified.

Thanks,
Elanchezhiyan P

**Comment by jakubpawlowicz** [comment]
Thanks for the fix @Elanchezhiyan-AIT - is this change going to land on main branch? What's the diff of the change you made?

**Comment by abdurrahmanyildirim** [comment]
I just saw the comments. I fixed that issue by deleting the icon not visible on the screen. That icon had 0 width and 0 height but there is no check for that case. The library checks the IsNaN case only. Adding `width === 0` was solving the problem. I don't remember well.

**Comment by musana** [comment]
Hi, I'm still getting the same issue on the latest version of html2canvas. Do you have any plans to fix the issue? I pull the code your repo therefore editing the code on my local environment will not work for me, unfortunately.
Thanks in advance.

**Comment by jakubpawlowicz** [comment]
@musana Here's the fix I applied manually to the main branch and got the code working in Firefox just fine. https://github.com/niklasvh/html2canvas/commit/48b426972ddedc5e54482618fd586d5e8094f52a HTH

**Comment by musana** [comment]
Hey @jakubpawlowicz ,

Is it possible to provide me a gzipped version of it? I will import it to my project using the script tag directly. Thanks

**Comment by jakubpawlowicz** [comment]
@musana As far as I remember that file https://github.com/niklasvh/html2canvas/issues/2697#issuecomment-1450039757 has the changes you need.

**Comment by musana** [comment]
Thank you @jakubpawlowicz 🙌

**Comment by bothness** [comment]
Can this issue please be reopened? I'm still getting this error in Firefox but not other browsers.

I'm using html2canvas on a client-side app using html2canvas.esm.js installed via NPM.

**Comment by dennismetz** [comment]
Unfortunately, the error still seems to be current.
I currently get it in FireFox as soon as there is a checkbox on the page. without a checkbox everything works fine.

**Comment by gbertoncelli** [comment]
@niklasvh is there any chance of a fix release ?
