### ISSUE TITLE
Text tags in SVG overlap (duplicated / doubling)

### ISSUE THREAD

**Issue by hyojin** [niklasvh/html2canvas#541]
(Sorry, I am not good at english)

Hello,
I am using this awesome script to render SVG tags
There is some text overlapping when I render the text tag in SVG to canvas
Text tag be processed as a Text node and also SVG
You can see that easily with transform property
![2015-02-19 15 08 29_2](https://cloud.githubusercontent.com/assets/3413183/6262820/b24fd5f4-b84e-11e4-87ed-01e6635da19a.png)
Here is sample code (with html2canvas 0.5.0-alpha2)

```
<html>
<head>
  <script src="https://code.jquery.com/jquery-1.11.2.min.js"></script>
  <script type="text/javascript" src="js/html2canvas.js"></script>
</head>
<body>
  <svg width="100" height="100">
    <g transform="translate(20,20)">
      <text dy=".45em" y="10" x="0" dx="-.8em" transform="translate(0,0) rotate(-70)" style="font-size:12px;">Text</text>
    </g>
  </svg>
  <script>
    $(document).ready(function() {
      html2canvas(document.body, {
        onrendered: function(canvas) {
          document.body.appendChild(canvas);
        }
      });
    })
  </script>
</body>
</html
```

And Here is my quick change

```
NodeParser.prototype.getChildren = function(parentContainer) {
    return flatten([].filter.call(parentContainer.node.childNodes, renderableNode).map(function(node) {
        var container = [node.nodeType === Node.TEXT_NODE && node.parentElement.tagName !== "text" ? new TextContainer(node, parentContainer) : new NodeContainer(node, parentContainer)].filter(nonIgnoredElement);
        return node.nodeType === Node.ELEMENT_NODE && container.length && node.tagName !== "TEXTAREA" ? (container[0].isElementVisible() ? container.concat(this.getChildren(container[0])) : []) : container;
    }, this));
};
```

I hope this will help

**Comment by sudhakargroup** [comment]
Thank you#Hyojin. That helps me.

**Comment by natee** [comment]
Thanks ,help me a lot!

**Comment by ncoquelet** [comment]
Thanks for your fix !

you can also check on tspan tagName :
node.nodeType === Node.TEXT_NODE && node.parentElement.tagName !== "text"  && node.parentElement.tagName !== "tspan"

**Comment by hyojin** [comment]
@ncoquelet I updated my [code](https://github.com/hyojin/html2canvas/commit/8fa0fa88ca21a832b82fc302e9b3dab3c9a89145). Thanks!

**Comment by ncoquelet** [comment]
@hyojin 
After test it on IE, your fix doesn't works because `parentElement` property is not populate on the current node. Use `parentNode` instead ! In any case, it will be more clear because we are into the `NodeParser` and it talk about node.

Otherwise, instead test on tag name, i change my code to test the instance of `parentNode` and process the current node has a `TextContainer` only if the parentNode isn't a `SVGElement`.

It works on chrome and ie11. on firefox i can't test it because of blank canvas bug !

My code 
```javascript
NodeParser.prototype.getChildren = function(parentContainer) {
    return flatten([].filter.call(parentContainer.node.childNodes, renderableNode).map(function(node) {
        var container = [node.nodeType === Node.TEXT_NODE && !(node.parentNode instanceof SVGElement) ? new TextContainer(node, parentContainer) : new NodeContainer(node, parentContainer)].filter(nonIgnoredElement);
        return node.nodeType === Node.ELEMENT_NODE && container.length && node.tagName !== "TEXTAREA" ? (container[0].isElementVisible() ? container.concat(this.getChildren(container[0])) : []) : container;
    }, this));
};
```

I hope this helps.

**Comment by ncoquelet** [comment]
fix my firefox problem, works on ff too :-)

**Comment by hyojin** [comment]
More clear!
I also checked that it works well on ff. 
I merged your fix and pull request was updated. Thanks :)

**Comment by berendberendsen** [comment]
@hyojin thanks for the investigation into this and the fix. I ran into the exact same problem the other day and I wasn't entirely sure what was causing it.

**Comment by Suchetana10** [comment]
I am not sure where I am getting confused here but I am getting the exception as "Uncaught ReferenceError: NodeParser is not defined"

**Comment by hyojin** [comment]
@Suchetana10 When did you get the exception? in loading script?

**Comment by vishwasvadavi** [comment]
@hyojin thank you.. worked for me

**Comment by nugen** [comment]
@hyojin thanks! works perfectly for me too

**Comment by hyojin** [comment]
@vishwasvadavi @nugen I'm happy to hear that! :)

**Comment by hyojin** [comment]
Some people still have the issue with text element, I change this issue opened and I will send PR again.

**Comment by seemasingh123** [comment]
![image](https://cloud.githubusercontent.com/assets/26019097/23330782/220e65c2-fb7d-11e6-8fd1-65e985bccc0c.png)

**Comment by seemasingh123** [comment]
<script type="text/javascript">	$(function(){	$('#PDFTABLE11').mouseover(function(){ div_content = document.querySelector("#container2") html2canvas(div_content).then(function(canvas) { data = canvas.toDataURL('image/png?'); save_img(data); }); });	}); function save_img(data){ $.post('save_jpg.php', {data: data}, function(res){ if(res != ''){ if(yes){ location.href =phe.php; } } else{ alert('something wrong'); } }); } </script>
![image](https://cloud.githubusercontent.com/assets/26019097/23330787/4ff77082-fb7d-11e6-8d0c-29adf2697b0c.png)

**Comment by theinventor** [comment]
Does anyone have a build of the library with this fix in it that I can test? Seeing same issue on highcharts page..

**Comment by Nywlem11** [comment]
Is this build available with the fix? I am still facing this issue with highcharts.

**Comment by sgsmittal** [comment]
Is this fix available in build or we have to create an override ?

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).

**Comment by aaronholla** [comment]
@niklasvh here is an example. I am still seeing this issue with v1.0.0-alpha.12. 

http://jsfiddle.net/qb83ngdb/

I'm a little confused as the pull request for this #616  was never merged but you are saying this is fixed in 1.0.0. Let me know if I am missing something? Thanks! :smile:

**Comment by karannagupta** [comment]
Dear @niklasvh ,

Thank you for this amazing library. I am able to reproduce this issue with the latest version - v1.0.0-rc.3

I have created an example on [CodePen here](https://codepen.io/karannagupta/pen/RXpddB) (Chrome only) where you will see that some of the text nodes (in the Graph title) are duplicated.

Steps to reproduce -
1. Please open the CodePen link - https://codepen.io/karannagupta/pen/RXpddB in Chrome only
2. Click on Copy to Clipboard button
3. Wait for the animation to finish (or see console for copied message)
4. Paste the graph in paint or a document (ctrl + v)

The graph titles are added on Line#193

Regards,
 Karan

<hr>
<img width="500" alt="text-duplication" src="https://user-images.githubusercontent.com/36845810/64604789-6741a080-d3e0-11e9-895b-e2a49427a40a.png">

**Comment by hyojin** [comment]
Hi @karannagupta 
Could you try [my branch](https://github.com/hyojin/html2canvas/tree/fix%23541/dist) to check whether it comes from the same reason?

**Comment by karannagupta** [comment]
Hi @hyojin 

With your version of the library (v0.5.0-alpha2) it doesn't work. You can test your [library on my Pen here](https://codepen.io/karannagupta/pen/RXpddB)

Also, I would like to use the latest version of html2canvas. I also don't need to use html2canvas.svg then.

Regards,
 Karan

**Comment by karannagupta** [comment]
Turns out it is an issue with Unicode fonts

![image](https://user-images.githubusercontent.com/36845810/64692361-8dd00c00-d4b2-11e9-8a90-5365659a9c1c.png)
