### ISSUE TITLE
Opacity

### ISSUE THREAD

**Issue by lmbuffetti** [niklasvh/html2canvas#717]
Hi,

I should create a canvas from webpage and I found your plugin, it works very well but I want say if it is possible to maintain the opacity of each element. In this moment it doesn't work.

Best Regards

**Comment by brcontainer** [comment]
It depends on how you are using the opacity. Put a example using jsfiddle.

**Comment by Dayjo** [comment]
I've been trying to get Opacity to work too and it doesn't appear to maintain it. 

I have an image in a div. The div has inline css `opacity: 0.78;` but on the screenshot it's 100% opaque.

**Comment by brcontainer** [comment]
@Dayjo Browser? OS? x86 or x64? Put a jsfiddle example please =)

**Comment by Dayjo** [comment]
OSX 10.11.4
Firefox 44.0.2
Chrome 49.0.2623.112 

Is html2canvas hosted on any CDNs so that I can include it on JSFiddle etc? As JSFiddle won't include the RAW version from Github :/

**Comment by chughes87** [comment]
Here is a jsFiddle exemplifying the issue: http://jsfiddle.net/tqqaa16x/. I'm struggling with this as well.

**Comment by JoolsCaesar** [comment]
Opacity doesn't seem to work with the simplest of examples:
https://jsfiddle.net/JoolsCaesar/yLj4qwe2/4/
https://jsfiddle.net/JoolsCaesar/yLj4qwe2/5/
(Tested in Chrome)

**Comment by niklasvh** [comment]
Fixed in https://github.com/niklasvh/html2canvas/tree/v1.0.0

**Comment by andywillekens** [comment]
@niklasvh Still having the same issue using version 1.0.0-alpha.12 I have a div with rounded corners, the website background is dark but on the saved image it has white corners when they should be transparent.

EXAMPLE:
![html2canvas_error](https://user-images.githubusercontent.com/5364383/40484046-76ab9400-5f5a-11e8-8070-af439a9e9194.gif)

**Comment by day** [comment]
This is also not working for me. Opacity is lost.

**Comment by hungpp250795** [comment]
@andy

> @niklasvh Still having the same issue using version 1.0.0-alpha.12 I have a div with rounded corners, the website background is dark but on the saved image it has white corners when they should be transparent.
> 
> EXAMPLE:
> ![html2canvas_error](https://user-images.githubusercontent.com/5364383/40484046-76ab9400-5f5a-11e8-8070-af439a9e9194.gif)

You should use the rgba(x,x,x,opacityValue) replace for opacity css style should be resolve your problem.

**Comment by NurulAlomAdor** [comment]
> Fixed in https://github.com/niklasvh/html2canvas/tree/v1.0.0

this link is not working now!

**Comment by fated-x** [comment]
I can confirm that opacity is still not working in the latest release: 1.0.0-rc.7. Perhaps we can get this ticket re-opened?

**Comment by NurulAlomAdor** [comment]
> I can confirm that opacity is still not working in the latest release: 1.0.0-rc.7. Perhaps we can get this ticket re-opened?

Use this version: https://github.com/niklasvh/html2canvas/suites/1187063696/artifacts/17429870 , Opacity will be work.

**Comment by fated-x** [comment]
> > I can confirm that opacity is still not working in the latest release: 1.0.0-rc.7. Perhaps we can get this ticket re-opened?
> 
> Use this version: https://github.com/niklasvh/html2canvas/suites/1187063696/artifacts/17429870 , Opacity will be work.

What exactly is this that you linked me to? I opened it up and it says it's v1.0.0-rc.7...

**Comment by NurulAlomAdor** [comment]
> > > I can confirm that opacity is still not working in the latest release: 1.0.0-rc.7. Perhaps we can get this ticket re-opened?
> > 
> > 
> > Use this version: https://github.com/niklasvh/html2canvas/suites/1187063696/artifacts/17429870 , Opacity will be work.
> 
> What exactly is this that you linked me to? I opened it up and it says it's v1.0.0-rc.7...

version name is same but in this js file, opacity bug is fixed.

**Comment by fated-x** [comment]
> > > > I can confirm that opacity is still not working in the latest release: 1.0.0-rc.7. Perhaps we can get this ticket re-opened?
> > > 
> > > 
> > > Use this version: https://github.com/niklasvh/html2canvas/suites/1187063696/artifacts/17429870 , Opacity will be work.
> > 
> > 
> > What exactly is this that you linked me to? I opened it up and it says it's v1.0.0-rc.7...
> 
> version name is same but in this js file, opacity bug is fixed.

Perhaps you could make a pull request so the entire community can benefit from this fix and we can continue to utilize yarn (or npm) for the html2canvas dependency?

**Comment by davidswinegar** [comment]
@niklasvh I just started using html2canvas in my project and it's great! But I am also running into this opacity bug - does the bundle above fix this issue / is there any chance you could release it and update the released npm package?

**Comment by jacobzirbel** [comment]
@davidswinegar this worked for me. The last number being the opacity

`background-color: rgba(25, 163, 71, .5); `

**Comment by rvirino** [comment]
> @davidswinegar this worked for me. The last number being the opacity
> 
> `background-color: rgba(25, 163, 71, .5); `

Yess! The best and fast solution! Thanks!!

**Comment by nik32** [comment]
> @davidswinegar this worked for me. The last number being the opacity
> 
> `background-color: rgba(25, 163, 71, .5); `

This worked for me even! Thanks for this great library @niklasvh!
