### ISSUE TITLE
Returns a blank image for any element when the document body is more than 30,000px tall.

### ISSUE THREAD

**Issue by charlie-lk** [niklasvh/html2canvas#882]
The library returns an empty image when the body of the document is more than 30,000px. You would try to capture an element of 100 x 100. But you get a blank image of the element is on a tall body.

Here is a fiddle which demonstrate this error. 

https://jsfiddle.net/fvo1xh8b/2/

You can change the body size less than 30,000 and it works fine.

**Comment by Sebastianvarv** [comment]
I have the exact same issue as you. Have you found any solution to this?

**Comment by charlie-lk** [comment]
http://stackoverflow.com/questions/37520013/html2canvas-returns-invalid-image-when-the-body-height-is-more-than-30000-pixels

**Comment by netweng** [comment]
emm,i got the same problem, but finally, i figure out!
in my case, here is my solution:
put an iframe in you body element, like 
```html
<html>
  <head>
  #canvas_handler {
   position:absolute;
   left: -10000px;
  }
  </head>
  <body>
  <iframe id="canvas_handler" />
  </body>
</html>
```

and every element you need to covert to canvas, you can copy and put them in this iframe, and use html2canvas, and then remove it, like this
```javascript
const copy_ele = origin_ele.cloneNode(true);
canvas_handler.appendChild(copy_ele);
canvas_handler.style.height = origin_ele.scrollHeight;
canvas_handler.style.width = origin_ele.scrollWidth;
html2canvas(copy_ele, {
      useCORS: true,
     }).then((canvas) => {
       // do your things
     });
canvas_handler.removeChild(table_ele);
```

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).

**Comment by AntonioDilorenzo** [comment]
hi when i try to screen an iframe with internal ip camera, it return a void image, please can you help me?

**Comment by leandrosouza0786** [comment]
@toadkicker brother, u save my code/job today hahahahahahahaht thanks a lot

**Comment by Liberateur** [comment]
@toadkicker Thanks !

**Comment by ricosmall** [comment]
> emm,i got the same problem, but finally, i figure out!
> in my case, here is my solution:
> put an iframe in you body element, like
> 
> ```
> <html>
>   <head>
>   #canvas_handler {
>    position:absolute;
>    left: -10000px;
>   }
>   </head>
>   <body>
>   <iframe id="canvas_handler" />
>   </body>
> </html>
> ```
> 
> and every element you need to covert to canvas, you can copy and put them in this iframe, and use html2canvas, and then remove it, like this
> 
> ```js
> const copy_ele = origin_ele.cloneNode(true);
> canvas_handler.appendChild(copy_ele);
> canvas_handler.style.height = origin_ele.scrollHeight;
> canvas_handler.style.width = origin_ele.scrollWidth;
> html2canvas(copy_ele, {
>       useCORS: true,
>      }).then((canvas) => {
>        // do your things
>      });
> canvas_handler.removeChild(table_ele);
> ```

I tried this method, but not work exactly. In my way, will work with code below:

```javascript
const copy_ele = origin_ele.cloneNode(true);
canvas_handler.contentDocument.body.appendChild(copy_ele);
canvas_handler.height = origin_ele.scrollHeight;
canvas_handler.width = origin_ele.scrollWidth;
html2canvas(canvas_handler.contentDocument.body, {
      useCORS: true,
     }).then((canvas) => {
       // do your things
     });
canvas_handler.removeChild(copy_ele);
```

And if you want to apply your css style like current document, you also need to copy to iframe:

```javascript
// add style
const link = document.createElement('link');
link.rel = 'stylesheet';
link.href = 'your_style_file_url.css';
canvas_handler.contentDocument.head.appendChild(link);

const copy_ele = origin_ele.cloneNode(true);
canvas_handler.contentDocument.body.appendChild(copy_ele);
canvas_handler.height = origin_ele.scrollHeight;
canvas_handler.width = origin_ele.scrollWidth;
html2canvas(canvas_handler.contentDocument.body, {
      useCORS: true,
     }).then((canvas) => {
       // do your things
     });
canvas_handler.removeChild(copy_ele);
```

**Comment by toadkicker** [comment]
Again this is a limitation in the browser itself and this library does not handle the error correctly. No coding solution besides limiting the number of pixels captured will change it.

**Comment by netweng** [comment]
> > emm,i got the same problem, but finally, i figure out!
> > in my case, here is my solution:
> > put an iframe in you body element, like
> > ```
> > <html>
> >   <head>
> >   #canvas_handler {
> >    position:absolute;
> >    left: -10000px;
> >   }
> >   </head>
> >   <body>
> >   <iframe id="canvas_handler" />
> >   </body>
> > </html>
> > ```
> > 
> > 
> > and every element you need to covert to canvas, you can copy and put them in this iframe, and use html2canvas, and then remove it, like this
> > ```js
> > const copy_ele = origin_ele.cloneNode(true);
> > canvas_handler.appendChild(copy_ele);
> > canvas_handler.style.height = origin_ele.scrollHeight;
> > canvas_handler.style.width = origin_ele.scrollWidth;
> > html2canvas(copy_ele, {
> >       useCORS: true,
> >      }).then((canvas) => {
> >        // do your things
> >      });
> > canvas_handler.removeChild(table_ele);
> > ```
> 
> I tried this method, but not work exactly. In my way, will work with code below:
> 
> ```js
> const copy_ele = origin_ele.cloneNode(true);
> canvas_handler.contentDocument.body.appendChild(copy_ele);
> canvas_handler.height = origin_ele.scrollHeight;
> canvas_handler.width = origin_ele.scrollWidth;
> html2canvas(canvas_handler.contentDocument.body, {
>   useCORS: true,
> }).then((canvas) => {
>   // do your things
>   canvas_handler.removeChild(copy_ele);
> });
> ```
> 
> And if you want to apply your css style the same as it in current document, you also need to copy style to iframe:
> 
> ```js
> // add style
> const link = document.createElement('link');
> link.rel = 'stylesheet';
> link.href = 'your_style_file_url.css';
> canvas_handler.contentDocument.head.appendChild(link);
> 
> const copy_ele = origin_ele.cloneNode(true);
> canvas_handler.contentDocument.body.appendChild(copy_ele);
> canvas_handler.height = origin_ele.scrollHeight;
> canvas_handler.width = origin_ele.scrollWidth;
> html2canvas(canvas_handler.contentDocument.body, {
>   useCORS: true,
> }).then((canvas) => {
>   // do your things
>   canvas_handler.removeChild(copy_ele);
> });
> ```

in my case, all elements are svg or inline style, so i don't need to append stylesheet. but yes, you should add your stylesheet if needed

**Comment by invisor** [comment]
I've faced the same issue. I needed to make an image from the modal window (with fixed position). I always received a white image. The problem was in the scroll position. This code works for me:
`const el = document.getElementById('html-to-canvas-area')
const area = el.getBoundingClientRect()
html2canvas(el, {
  scrollX: 0,
  scrollY: 0,
  width: area.width,
  height: area.height
})`

**Comment by flaviostutz** [comment]
Worked for me like a charm! Thanks for the clever solution!

**Comment by MEGApixel23** [comment]
@invisor lifesaver! That's the only thing that worked for me.

**Comment by seahindeniz** [comment]
These option might also a solution for scrolling related cases
```js
{
  scrollX: 0,
  scrollY: -window.scrollY
}

```

**Comment by ard-dev** [comment]
This worked for me.

**Comment by DamianoMazzara** [comment]
I've tried all your workarounds and no one worked for me.
Finally I just added `window.scrollTo(0, 0);` before html2canvaS() function and it works.
The error was the scrolling page with fixed navs in my website (sbAdmin template).
I really hope it can help other poeple with my issue.

Entire code:
```js
window.scrollTo(0, 0);
    html2canvas(document.getElementById("div_to_download_as_image"), {}).then(function (
      canvas
    ) {
      let a = document.createElement("a");
      a.href = canvas.toDataURL("image/jpg");
      a.download = "My file name.jpg";
      a.click();
      a.remove();
    });

**Comment by GabrielMoraisSisdado** [comment]
{
    scrollX: 0,
    scrollY: -window.scrollY
}

pass to the function

**Comment by GabrielMoraisSisdado** [comment]
Try adding

{
    scrollX: 0,
    scrollY: -window.scrollY
}
to the html2canvas options

credits to https://stackoverflow.com/questions/57936607/why-there-is-a-white-space-on-the-top-on-html2canvas

**Comment by vargas055** [comment]
@DamianoMazzara Yours was the one solution that after hours and hours worked for me kudos dude!!!

**Comment by mboullouz** [comment]
I have 4 divs I want to screenshot each separately in the page, 
-  the fist 2 are visibles directly without scroll, so the screenshot is correct 
- the seconds divs which need a small scroll to be visible, when screenshot , they are empty or blank.

I tried all solutions provided there, some solutions work (by using options on size, X position, Y position..) but hey have the disadvantage of capturing only some part of the "div" depending on the scrolling!
My understanding is that: the screenshot library capture only at best the part which is visible, not the whole HtmlElement that is provided as argument.
Can someone correct me please ?

**Comment by 1der1** [comment]
You can only capture visible parts.
The scrollX and scrollY parameters are a must. 

However, I had other issues with empty canvas or cut elements.
I fixed everything by going back to version 0.5.

**Comment by iamk3nnyt** [comment]
This issue should be reopened as I'm still experiencing the same behavior of blank white canvas. None of the solutions provided so far has helped

**Comment by tmasabari** [comment]
I am also facing a similar issue. I tried all the above workarounds. I am printing multiple pages, the first page is partially visible on the screen. But when I produce the screenshots individually for each page, except the last page all the other pages are blank.
